services:
  lavalink:
    image: fredboat/lavalink:4.0.5
    container_name: lavalink
    restart: on-failure
    ports:
      - "2333:2333"
    volumes:
      - /opt/Lavalink/application.yml:/opt/Lavalink/application.yml
      - /opt/Lavalink/plugins/:/opt/Lavalink/plugins/
  wokkibot:
    image: wokkipannu/wokkibot-go:latest
    container_name: wokkibot
    restart: always
    volumes:
      - /opt/Wokkibot/.env:/.env
