services:
  lavalink:
    image: fredboat/lavalink:master
    container_name: lavalink
    restart: always
    ports:
      - "2333:2333"
    volumes:
      - /opt/Lavalink/application.yml:/opt/Lavalink/application.yml
  wokkibot:
    image: wokkipannu/wokkibot-go:latest
    container_name: wokkibot
    restart: always
    volumes:
      - /opt/Wokkibot/.env:/wokkibot/.env
