name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.FOLDER }}
          git pull
          export GIT_COMMIT=$(git rev-parse --short HEAD)
          sudo -E docker compose build --build-arg GIT_COMMIT=$GIT_COMMIT wokkibot
          sudo docker compose up -d --no-deps wokkibot